force-app/main/default/objects/Clinical_Study__c/Clinical_Study__c.object-meta.xml
<CustomObject>
    <label>Clinical Study</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Clinical Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/Study_Participant__c.object-meta.xml
<CustomObject>
    <label>Study Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Study Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/fields/Clinical_Study__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Study</label>
    <referenceTo>Clinical_Study__c</referenceTo>
    <relationshipLabel>Study Participants</relationshipLabel>
    <relationshipName>Study_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Study Participants</relationshipLabel>
    <relationshipName>Study_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/fields/Study_Participant_Key__c.field-meta.xml
<CustomField>
    <fullName>Study_Participant_Key__c</fullName>
    <label>Study Participant Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/triggers-lesson/classes/StudyParticipantTriggerHandler.cls
/**
 * Created by user on 02.09.2019.
 */

public with sharing class StudyParticipantTriggerHandler {

    public static void updateStudyParticipantKey(List <Study_Participant__c> spList){

        Set<Id> clinicalStudyIds = new Set<Id>();

        for (Study_Participant__c sp : spList) clinicalStudyIds.add(sp.Clinical_Study__c);


        List<Clinical_Study__c> clinicalStudies = [
                SELECT Id, Name
                FROM Clinical_Study__c
                WHERE Id IN : clinicalStudyIds
        ];

        //var1
        Map<Id, Clinical_Study__c> clinicalStudyMap = new Map<Id, Clinical_Study__c>();
        for (Clinical_Study__c clinicalStudy : clinicalStudies) clinicalStudyMap.put(clinicalStudy.Id, clinicalStudy);

        //var2
        //clinicalStudyMap = new Map<Id, Clinical_Study__c>(clinicalStudies);

        for (Study_Participant__c sp : spList) {
            String studyName = clinicalStudyMap.get(sp.Clinical_Study__c).Name;
            sp.Study_Participant_Key__c = sp.Contact__c + ' ' + studyName;
        }
    }
}