force-app/main/default/objects/Clinical_Study__c/Clinical_Study__c.object-meta.xml
<CustomObject>
    <label>Clinical Study</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Clinical Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/Study_Participant__c.object-meta.xml
<CustomObject>
    <label>Study Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Study Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/fields/Clinical_Study__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Study</label>
    <referenceTo>Clinical_Study__c</referenceTo>
    <relationshipLabel>Study Participants</relationshipLabel>
    <relationshipName>Study_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Study Participants</relationshipLabel>
    <relationshipName>Study_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/lightning-components-lesson/classes/StudyParticipantFilter.cls
/**
 * Created by Dmitry Bobylev on 05.09.2019.
 */

public with sharing class StudyParticipantFilter implements SearchFilter{
    @AuraEnabled public String status;
    @AuraEnabled public String studyTitleTerm;

    public List<String> getFields() {
        return new List<String>{
                'Contact__r.Name',
                'Clinical_Study__r.Title__c'
        };
    }

    public SObjectType getSObjectType() {
        return Study_Participant__c.getSObjectType();
    }

    public String getFilterString() {
        return ' WHERE Status__c = \'' + status + '\' AND Clinical_Study__r.Title__c LIKE \'%' + studyTitleTerm +'%\' ';
    }
}