force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>ER-{0000}</displayFormat>
        <label>Exchange Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/integration-lesson/classes/Schedule_UpdateRates.cls
/**
 * Created by Dmitry Bobylev on 09.09.2019.
 */

public with sharing class Schedule_UpdateRates implements Schedulable {

    public void execute(SchedulableContext sc) {
        GetRates getRatesRemoteCall = new GetRates('USD');
        Map<String, Decimal> remoteRates = (Map<String, Decimal>) getRatesRemoteCall.execute();

        List<Exchange_Rate__c> exchangeRates = [SELECT Id, Currency__c, Rate__c FROM Exchange_Rate__c];
        Map<String, Exchange_Rate__c> exchangeRatesMap = new Map<String, Exchange_Rate__c>();
        for (Exchange_Rate__c rate : exchangeRates) exchangeRatesMap.put(rate.Currency__c, rate);

        List<Exchange_Rate__c> ratesToUpsert = new List<Exchange_Rate__c>();
        for (String curr : remoteRates.keySet()) {
            Exchange_Rate__c exchangeRate = exchangeRatesMap.get(curr);
            if (exchangeRate == null) {
                exchangeRate = new Exchange_Rate__c(
                        Currency__c = curr,
                        Rate__c = remoteRates.get(curr)
                );
            } else {
                exchangeRate.Rate__c = remoteRates.get(curr);
            }
            ratesToUpsert.add(exchangeRate);
        }
        upsert ratesToUpsert;
    }

}